CREATE TABLE IF NOT EXISTS game (
    game_id             UUID PRIMARY KEY,
    name                TEXT NOT NULL,
    version             TEXT NOT NULL,
    released            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (name, version)
);

CREATE TABLE IF NOT EXISTS score (
    score_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    points             INT NOT NULL,
    player             TEXT NOT NULL,
    achieved           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    game_id            UUID REFERENCES game (game_id) ON DELETE CASCADE
);

INSERT INTO game (game_id, name, version) VALUES ('8bee6702-4d17-4134-a99e-d21158b66bc4', 'Spooky Speech Spells', 'v0.1');